name: todo_client
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.3
  flutter_riverpod: ^2.3.2
  go_router: ^6.5.0
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  custom_lint:
  riverpod_lint: ^1.1.5

flutter:
  uses-material-design: true
