name: todo_client
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.3
  rive: ^0.10.3
  flutter_riverpod: ^2.3.2
  go_router: ^6.5.0
  collection: ^1.17.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  lottie: ^2.3.1
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  custom_lint:
  freezed: ^2.3.2
  build_runner: ^2.3.3
  riverpod_lint: ^1.1.5
  json_serializable: ^6.6.1
  intl: ^0.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/lottie/
    - assets/images/
