name: todo_client
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  # Network handling!
  dio: ^5.3.2
  # State management!
  flutter_riverpod: ^2.3.2
  # Route handling!
  go_router: ^13.2.0
  # Utilities!
  intl: ^0.19.0
  envied: ^0.5.3
  animations: ^2.0.7
  collection: ^1.18.0
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  # Helpers!
  lottie: ^3.1.0
  rive: ^0.12.4
  flutter_portal: ^1.1.4
  google_fonts: ^6.2.0
  fresh_dio: ^0.4.1
  country_picker: ^2.0.25
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  freezed: ^2.4.2
  build_runner: ^2.4.6
  json_serializable: ^6.6.1
  envied_generator: ^0.5.3
  custom_lint: ^0.6.2
  riverpod_lint: ^2.0.4

# dependency_overrides:
#   analyzer: ^6.0.0 # Conflicted between (Envied) & (Freezed)!
#   collection: ^1.18.0 # Conflicted with (flutter_test)!

flutter:
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/icons/
    - assets/lottie/
    - assets/images/
