name: TODO-Web-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: todo_client
          targetBranch: client-host
          webRenderer: canvaskit
          baseHref: /full-stack-todo/