name: TODO-Web-Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Clean the project directory and get deps!
      #   if: github.ref == 'refs/heads/main'
      #   run: flutter clean && flutter pub get
      #   working-directory: todo_client
      # - name: Generate all the [build-runner] files!
      #   if: github.ref == 'refs/heads/main'
      #   run: dart run build_runner build --delete-conflicting-outputs
      #   working-directory: todo_client
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: todo_client
          targetBranch: client-host
          webRenderer: canvaskit
          baseHref: /full-stack-todo/
